
public class RomanNumerals {

	public String toRoman(int nmber) {
		if (nmber == 1)
			return "I";
		if (nmber==2)
			return "II";
		if (nmber==3)
			return "III";
		if (nmber==4)
			return "IV";
		if (nmber==5)
			return "V";
		if (nmber==6)
			return "VI";
		if (nmber==7)
			return "VII";
		if (nmber==8)
			return "VIII";
		if (nmber==9)
			return "IX";
		if (nmber==10)
			return "X";
		if (nmber==11)
			return "XI";
		if (nmber==12)
			return "XII";
		if (nmber==13)
			return "XIII";
		if (nmber==14)
			return "XIV";
		if (nmber==15)
			return "XV";
		if (nmber==16)
			return "XVI";
		if (nmber==17)
			return "XVII";
		if (nmber==18)
			return "XVIII";
		if (nmber==19)
			return "XIX";
		if (nmber==20)
			return "XX";
		if (nmber==21)
			return "XXI";
		if (nmber==22)
			return "XXII";
		if (nmber==23)
			return "XXIII";
		if (nmber==24)
			return "XXIV";
		if (nmber==25)
			return "XXV";
		if (nmber==26)
			return "XXVI";
		if (nmber==27)
			return "XXVII";
		if (nmber==28)
			return "XXVIII";
		if (nmber==29)
			return "XXIX";
		if (nmber==30)
			return "XXX";
		if (nmber==31)
			return "XXXI";
		if (nmber==32)
			return "XXXII";
		if (nmber==33)
			return "XXXIII";
		if (nmber==34)
			return "XXXIV";
		if (nmber==35)
			return "XXXV";
		if (nmber==36)
			return "XXXVI";
		if (nmber==37)
			return "XXXVII";
		if (nmber==38)
			return "XXXVIII";
		if (nmber==39)
			return "XXXIX";
		if (nmber==40)
			return "XL";
		if (nmber==41)
			return "XLI";
		if (nmber==42)
			return "XLII";
		if (nmber==43)
			return "XLIII";
		if (nmber==44)
			return "XLIV";
		if (nmber==45)
			return "XLV";
		if (nmber==46)
			return "XLVI";
		if (nmber==47)
			return "XLVII";
		if (nmber==48)
			return "XLVIII";
		if (nmber==49)
			return "XLIX";
		if (nmber==50)
			return "L";
		if (nmber==51)
			return "LI";
		if (nmber==52)
			return "LII";
		if (nmber==53)
			return "LIII";
		if (nmber==54)
			return "LIV";
		if (nmber==55)
			return "LV";
		if (nmber==56)
			return "LVI";
		if (nmber==57)
			return "LVII";
		if (nmber==58)
			return "LVIII";
		if (nmber==59)
			return "LIX";
		if (nmber==60)
			return "LX";
		if (nmber==61)
			return "LXI";
		if (nmber==62)
			return "LXII";
		if (nmber==63)
			return "LXIII";
		if (nmber==64)
			return "LXIV";
		if (nmber==65)
			return "LXV";
		if (nmber==66)
			return "LXVI";
		if (nmber==67)
			return "LXVII";
		if (nmber==68)
			return "LXVIII";
		if (nmber==69)
			return "LXIX";
		
		return null;
	}

}
